name: Scheduled API Data Fetch and Commit

on:
  schedule:
    - cron: "0 0 * * *"
jobs:
  run-every-day:
    runs-on: ubuntu-latest

    steps:
    - name: Run a script
      run: |
        echo "This is running every day at $(date)"
