name: Scheduled API Data Fetch and Commit

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  run-every-day:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install requests

    # Run your Python script
    - name: Run Python script
      run: |
        python retrieve-cards.py

    # Configure git user for commits
    - name: Set up git user
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"

    # Commit the changes
    - name: Commit changes
      run: |
        git add .
        git commit -m "Auto commit: API data update at $(date)"
    
    # Push changes to the repository
    - name: Push changes
      run: git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
